### ISSUE TITLE
Cassandra Worker

### ISSUE THREAD

**Issue by vajda** [smartcat-labs/berserker#25]
Provide cassandra worker implementation.

It should support following configuration options:

- Consistency level (still to decide on whether it will be global, or per request)
- Bootstrap commands (create keyspace, create tables) this should execute once at the worker initialization
- Cassandra hosts (servers to connect to)
- Async/sync execution of CQL queriees
- Desing wise, it would be better to have list of prepared statements where data source would provide map of values to inject into prepared statement and prepared statement id to use

**Comment by nivancevic** [comment]
Even if CL is global, it would be good to have Read CL and Write CL separated.

**Comment by nivancevic** [comment]
Although the bootstrap CQL statements feature might seem optional, it helps making Berserker user-friendly.

**Comment by vajda** [comment]
I would go with per request CL. If we are to have statement ID and map of values, it is easy to add consistency level as well for that contract. So the data source would need to provide something like:
```
values: <mapWithValues>
consistencyLevel: ONE
statementID: 12
```

**Comment by nivancevic** [comment]
And for cases without prepared statements, the map could look like this:
```
statement: "CQL statement"
consistencyLevel: ONE
```

**Comment by vajda** [comment]
Yes, I would say so.
